package com.happytails.social;

import jakarta.servlet.http.HttpSession;
import org.springframework.core.io.ClassPathResource;
import org.springframework.http.*;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import java.io.IOException;
import java.nio.charset.StandardCharsets;

@Controller
public class AppPageController {
  @GetMapping({"/","/app"})
  public ResponseEntity<?> app(HttpSession session) throws IOException {
    Object owner=session.getAttribute("ownerId");
    if(owner==null)return ResponseEntity.status(HttpStatus.FOUND).header(HttpHeaders.LOCATION,"/login.html").build();
    Object active=session.getAttribute("activePetId");
    if(!(active instanceof Long))return ResponseEntity.status(HttpStatus.FOUND).header(HttpHeaders.LOCATION,"/login.html?manage=1").build();
    String html=new String(new ClassPathResource("static/index.html").getInputStream().readAllBytes(), StandardCharsets.UTF_8);
    html=html.replace("const API='/api/social';let me=1,","const API='/api/social';let me="+active+",");
    html=html.replace("<div class=\"top-actions\">","<div class=\"top-actions\"><button class=\"icon-btn\" title=\"Switch pet\" onclick=\"location.href='/login.html?manage=1'\">🐾</button><button class=\"icon-btn\" title=\"Log out\" onclick=\"fetch('/api/auth/logout',{method:'POST'}).then(()=>location.href='/login.html')\">↪</button>");
    String hardening="""
<style>
.shop-hero{background:linear-gradient(120deg,#5f31d9,#8c4de9 48%,#ff6e9b);color:#fff;border-radius:24px;padding:28px;margin-bottom:18px;display:grid;grid-template-columns:1fr auto;align-items:center;gap:20px;overflow:hidden;position:relative}.shop-hero:after{content:'🐾';position:absolute;right:90px;top:-50px;font-size:190px;opacity:.08}.shop-hero h2{font-size:30px;margin:0 0 8px}.shop-hero p{margin:0;opacity:.9}.shop-hero .cart-btn{background:#fff;color:#5f31d9;border:0;border-radius:14px;padding:13px 18px;font-weight:900;cursor:pointer}.shop-tools{display:flex;gap:10px;flex-wrap:wrap;align-items:center;margin:15px 0}.shop-search{flex:1;min-width:230px;padding:12px 14px;border:1px solid #ddd9ea;border-radius:13px}.cat-chip{border:1px solid #e7e1f5;background:#fff;color:#5c5671;border-radius:999px;padding:9px 13px;font-weight:750;cursor:pointer}.cat-chip.active{background:#6d36e3;color:#fff}.market-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:15px}.market-card{padding:0;overflow:hidden}.market-img{height:165px;display:grid;place-items:center;font-size:72px;background:linear-gradient(145deg,#f6f1ff,#fff3f7);position:relative}.market-badge{position:absolute;left:10px;top:10px;background:#fff;color:#6d36e3;padding:5px 8px;border-radius:999px;font-size:10px;font-weight:900}.wish{position:absolute;right:10px;top:10px;width:34px;height:34px;border:0;border-radius:50%;background:#fff}.market-info{padding:15px}.market-info h3{font-size:16px}.rating{font-size:12px;color:#8a819a}.market-price b{font-size:21px;color:#5f31d9}.old-price{text-decoration:line-through;color:#aaa;font-size:12px;margin-left:6px}.product-actions{display:grid;grid-template-columns:1fr auto;gap:8px}.product-actions button{border:0;border-radius:11px;padding:10px;font-weight:800}.add-cart{background:#6d36e3;color:#fff}.view-product{background:#f2edff;color:#6d36e3}.recommend-strip{display:flex;gap:10px;overflow:auto;margin:15px 0 20px}.recommend-pill{min-width:max-content;padding:10px 14px;background:#fff7df;border:1px solid #ffe5a0;border-radius:13px;font-size:12px}@media(max-width:1200px){.market-grid{grid-template-columns:repeat(3,1fr)}}@media(max-width:850px){.market-grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:540px){.market-grid{grid-template-columns:1fr}}
</style>
<script>
(function(){
 const samePet=p=>p&&Number(p.id)===Number(me);const petPic=p=>p&&p.avatarUrl?`<img src="${p.avatarUrl}" alt="${esc(p.name)}" style="width:100%;height:100%;object-fit:cover;border-radius:inherit">`:petEmoji(p?.species);const originalFollow=followPet,originalFriend=friendPet;
 followPet=async function(id,b){if(Number(id)===Number(me)){toast('You cannot follow your own pet profile.');return;}return originalFollow(id,b)};friendPet=async function(id){if(Number(id)===Number(me)){toast('You cannot send a friend request to your own pet profile.');return;}return originalFriend(id)};
 renderDiscover=function(list){const safe=(list||profiles).filter(p=>!samePet(p));discoverGrid.innerHTML=safe.map(p=>`<div class="card pet-card"><div class="pet-hero" style="overflow:hidden">${petPic(p)}</div><h3>${esc(p.name)} ✓</h3><div class="handle">${esc(p.handle)}</div><p>${esc(p.breed||p.species)} · ${esc(p.location||'Nearby')}</p><span class="pill">${esc(p.species||'Pet')}</span>${p.age!=null?`<span class="pill">${p.age} yrs</span>`:''}<span class="pill">${p.followers} followers</span><div class="pet-actions"><button class="btn ghost" onclick="followPet(${p.id},this)">Follow</button><button class="btn primary" onclick="friendPet(${p.id})">Friend Request</button></div></div>`).join('')||'<div class="card empty">No other pets match your search.</div>'};
 openPlayDate=function(){const options=profiles.filter(p=>!samePet(p)).map(p=>`<option value="${p.id}">${esc(p.name)} · ${esc(p.breed||p.species)}</option>`).join('');if(!options){toast('Add or discover another pet before scheduling a play date.');return;}openModal('Schedule Play Date',`<form class="form" onsubmit="createPlayDate(event)"><select id="playGuest" required>${options}</select><input id="playPlace" required placeholder="Pet-friendly park or venue"><input id="playTime" type="datetime-local" required><button class="btn primary">Schedule Play Date 🎾</button></form>`)};
 const catalog=[{id:1,name:'Bouncy Rope Ball',icon:'🎾',cat:'Toys',price:12.99,pets:'Dogs'},{id:2,name:'Interactive Treat Puzzle',icon:'🧩',cat:'Toys',price:18.50,pets:'Dogs & Cats'},{id:3,name:'Salmon Training Bites',icon:'🐟',cat:'Snacks',price:11.99,pets:'Dogs & Cats'},{id:4,name:'Cozy Knit Pet Hoodie',icon:'🧥',cat:'Fashion',price:26.99,pets:'Dogs & Cats'},{id:5,name:'Happy Tails Gift Box',icon:'🎁',cat:'Gifts',price:34.99,pets:'All Pets'},{id:6,name:'Gentle Grooming Kit',icon:'🧴',cat:'Care',price:27.75,pets:'Dogs & Cats'},{id:7,name:'Travel Water Bottle',icon:'💧',cat:'Travel',price:17.49,pets:'Dogs'},{id:8,name:'Cloud Comfort Bed',icon:'🛏️',cat:'Home',price:44.99,pets:'Dogs & Cats'},{id:9,name:'Bird Foraging Set',icon:'🦜',cat:'Small Pets',price:18.25,pets:'Birds'},{id:10,name:'Rabbit Tunnel',icon:'🐇',cat:'Small Pets',price:21.99,pets:'Rabbits'}];let shopCategory='All',shopQuery='',cart=[];
 window.setShopCategory=c=>{shopCategory=c;renderShop()};window.searchShop=v=>{shopQuery=v.toLowerCase();renderShop()};window.addToCart=id=>{const p=catalog.find(x=>x.id===id);cart.push(p);toast(p.name+' added to cart 🛍');renderShop()};window.renderShop=function(){const shop=document.getElementById('view-shop');if(!shop)return;const mine=profile(me),items=catalog.filter(p=>(shopCategory==='All'||p.cat===shopCategory)&&(!shopQuery||p.name.toLowerCase().includes(shopQuery)));shop.innerHTML=`<div class="shop-hero"><div><h2>🛍 Happy Tails Marketplace</h2><p>Small, personalized shopping space for ${esc(mine.name)} — toys, snacks, outfits, gifts and care.</p></div><button class="cart-btn">🛒 ${cart.length}</button></div><div class="shop-tools"><input class="shop-search" oninput="searchShop(this.value)" placeholder="Search pet products..."></div><div class="shop-tools">${['All','Toys','Snacks','Fashion','Gifts','Care','Travel','Home','Small Pets'].map(c=>`<button class="cat-chip ${shopCategory===c?'active':''}" onclick="setShopCategory('${c}')">${c}</button>`).join('')}</div><div class="market-grid">${items.map(p=>`<article class="card market-card"><div class="market-img">${p.icon}</div><div class="market-info"><span class="pill">${p.cat}</span><h3>${esc(p.name)}</h3><div class="rating">For ${esc(p.pets)}</div><div class="market-price"><b>$${p.price.toFixed(2)}</b></div><div class="product-actions"><button class="add-cart" onclick="addToCart(${p.id})">Add to Cart</button></div></div></article>`).join('')}</div>`};
})();
</script>
""";
    html=html.replace("</body>",hardening+"</body>");
    html=html.replace("</head>","<link rel=\"stylesheet\" href=\"/product-ux.css\"></head>");
    html=html.replace("</body>","<script src=\"/product-ux.js\"></script><script src=\"/profile-editor.js\"></script></body>");
    return ResponseEntity.ok().contentType(MediaType.TEXT_HTML).body(html);
  }
}
