package com.happytails.social;

import jakarta.persistence.*;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpSession;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.http.*;
import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;
import org.springframework.web.bind.annotation.*;
import java.time.*;
import java.util.*;

@Entity @Table(name="owner_accounts") class OwnerAccount {@Id @GeneratedValue(strategy=GenerationType.IDENTITY) Long id;@Column(nullable=false,unique=true) String email;@Column(nullable=false) String passwordHash;String displayName;LocalDateTime createdAt=LocalDateTime.now();public Long getId(){return id;}public String getEmail(){return email;}public void setEmail(String v){email=v;}public String getPasswordHash(){return passwordHash;}public void setPasswordHash(String v){passwordHash=v;}public String getDisplayName(){return displayName;}public void setDisplayName(String v){displayName=v;}}
@Entity @Table(name="owner_pet_links",uniqueConstraints=@UniqueConstraint(columnNames={"ownerId","petProfileId"})) class OwnerPetLink {@Id @GeneratedValue(strategy=GenerationType.IDENTITY) Long id;Long ownerId;Long petProfileId;public Long getId(){return id;}public Long getOwnerId(){return ownerId;}public void setOwnerId(Long v){ownerId=v;}public Long getPetProfileId(){return petProfileId;}public void setPetProfileId(Long v){petProfileId=v;}}
interface OwnerAccountRepository extends JpaRepository<OwnerAccount,Long>{Optional<OwnerAccount> findByEmailIgnoreCase(String email);boolean existsByEmailIgnoreCase(String email);}
interface OwnerPetLinkRepository extends JpaRepository<OwnerPetLink,Long>{List<OwnerPetLink> findByOwnerId(Long ownerId);boolean existsByOwnerIdAndPetProfileId(Long ownerId,Long petProfileId);Optional<OwnerPetLink> findByOwnerIdAndPetProfileId(Long ownerId,Long petProfileId);}

@RestController @RequestMapping("/api/auth")
public class AuthController {
 private static final int SESSION_IDLE_SECONDS=86400;
 private final OwnerAccountRepository owners;private final OwnerPetLinkRepository links;private final PetProfileRepository profiles;private final BCryptPasswordEncoder encoder=new BCryptPasswordEncoder(10);
 public AuthController(OwnerAccountRepository owners,OwnerPetLinkRepository links,PetProfileRepository profiles){this.owners=owners;this.links=links;this.profiles=profiles;}
 @PostMapping("/signup") public ResponseEntity<?> signup(@RequestBody Map<String,String> body,HttpServletRequest request){HttpSession session=request.getSession(true);String email=norm(body.get("email")),password=body.getOrDefault("password",""),name=body.getOrDefault("displayName","").trim();if(email.isBlank()||!email.matches("^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$"))return bad("Enter a valid email address.");String passwordError=passwordError(password);if(passwordError!=null)return bad(passwordError);if(owners.existsByEmailIgnoreCase(email))return ResponseEntity.status(409).body(Map.of("error","Unable to create account with those details."));OwnerAccount o=new OwnerAccount();o.setEmail(email);o.setPasswordHash(encoder.encode(password));o.setDisplayName(name.isBlank()?"Pet Parent":name);o=owners.save(o);session.setAttribute("ownerId",o.getId());session.removeAttribute("activePetId");secureAuthenticatedSession(request,session);return ResponseEntity.status(201).body(sessionPayload(o,session));}
 @PostMapping("/login") public ResponseEntity<?> login(@RequestBody Map<String,String> body,HttpServletRequest request){HttpSession session=request.getSession(true);String email=norm(body.get("email")),password=body.getOrDefault("password","");Optional<OwnerAccount> found=owners.findByEmailIgnoreCase(email);if(found.isEmpty()||!encoder.matches(password,found.get().getPasswordHash()))return ResponseEntity.status(401).body(Map.of("error","Incorrect email or password."));OwnerAccount o=found.get();session.setAttribute("ownerId",o.getId());List<PetProfile> pets=petsFor(o.getId());Long current=activePet(session);if(current==null||!links.existsByOwnerIdAndPetProfileId(o.getId(),current)){if(pets.isEmpty())session.removeAttribute("activePetId");else session.setAttribute("activePetId",pets.get(0).getId());}secureAuthenticatedSession(request,session);return ResponseEntity.ok(sessionPayload(o,session));}
 @PostMapping("/change-password") public ResponseEntity<?> changePassword(@RequestBody Map<String,String> body,HttpServletRequest request){HttpSession session=request.getSession(false);Long ownerId=ownerId(session);if(ownerId==null)return unauthorized();OwnerAccount owner=owners.findById(ownerId).orElse(null);if(owner==null){session.invalidate();return unauthorized();}String current=body.getOrDefault("currentPassword",""),next=body.getOrDefault("newPassword","");if(!encoder.matches(current,owner.getPasswordHash()))return ResponseEntity.status(401).body(Map.of("error","Current password is incorrect."));String passwordError=passwordError(next);if(passwordError!=null)return bad(passwordError);if(encoder.matches(next,owner.getPasswordHash()))return bad("New password must be different from your current password.");owner.setPasswordHash(encoder.encode(next));owners.save(owner);secureAuthenticatedSession(request,session);return ResponseEntity.ok(Map.of("ok",true,"message","Password updated."));}
 @PostMapping("/logout") public ResponseEntity<?> logout(HttpServletRequest request){HttpSession session=request.getSession(false);if(session!=null)session.invalidate();return ResponseEntity.ok().header(HttpHeaders.SET_COOKIE,"JSESSIONID=; Path=/; Max-Age=0; HttpOnly; SameSite=Lax").body(Map.of("ok",true));}
 @GetMapping("/session") public ResponseEntity<?> current(HttpSession session){Long ownerId=ownerId(session);if(ownerId==null)return ResponseEntity.status(401).body(Map.of("loggedIn",false));return owners.findById(ownerId).<ResponseEntity<?>>map(o->ResponseEntity.ok(sessionPayload(o,session))).orElseGet(()->ResponseEntity.status(401).body(Map.of("loggedIn",false)));}
 @GetMapping("/pets") public ResponseEntity<?> pets(HttpSession session){Long ownerId=ownerId(session);if(ownerId==null)return unauthorized();return ResponseEntity.ok(petsFor(ownerId));}
 @PostMapping("/pets") public ResponseEntity<?> createPet(@RequestBody PetProfile p,HttpSession session){Long ownerId=ownerId(session);if(ownerId==null)return unauthorized();ResponseEntity<?> validation=validateProfile(p,true);if(validation!=null)return validation;normalizeProfile(p);p.setFollowers(0);p.setFollowing(0);try{PetProfile saved=profiles.save(p);OwnerPetLink link=new OwnerPetLink();link.setOwnerId(ownerId);link.setPetProfileId(saved.getId());links.save(link);session.setAttribute("activePetId",saved.getId());return ResponseEntity.status(201).body(saved);}catch(DataIntegrityViolationException e){return ResponseEntity.status(409).body(Map.of("error","That pet username is already taken."));}}
 @PutMapping("/pets/{petId}") public ResponseEntity<?> updatePet(@PathVariable Long petId,@RequestBody PetProfile in,HttpSession session){Long ownerId=ownerId(session);if(ownerId==null)return unauthorized();if(!links.existsByOwnerIdAndPetProfileId(ownerId,petId))return ResponseEntity.status(403).body(Map.of("error","This pet does not belong to your account."));ResponseEntity<?> validation=validateProfile(in,false);if(validation!=null)return validation;return profiles.findById(petId).<ResponseEntity<?>>map(p->{if(in.getName()!=null&&!in.getName().isBlank())p.setName(in.getName().trim());if(in.getHandle()!=null&&!in.getHandle().isBlank())p.setHandle(normalizeHandle(in.getHandle()));p.setSpecies(clean(in.getSpecies()));p.setBreed(clean(in.getBreed()));p.setBio(clean(in.getBio()));p.setLocation(clean(in.getLocation()));p.setBirthday(in.getBirthday());p.setAdoptionDate(in.getAdoptionDate());p.setAge(calculateAge(in.getBirthday(),in.getAge()));p.setGender(clean(in.getGender()));p.setPersonality(clean(in.getPersonality()));p.setFavoriteActivities(clean(in.getFavoriteActivities()));p.setPetPreferences(clean(in.getPetPreferences()));p.setPrivateAccount(in.isPrivateAccount());p.setShowLocation(in.isShowLocation());p.setMessagePermission(permission(in.getMessagePermission()));p.setPlayDatePermission(permission(in.getPlayDatePermission()));if(in.getAvatarUrl()!=null&&!in.getAvatarUrl().isBlank())p.setAvatarUrl(in.getAvatarUrl());try{return ResponseEntity.ok(profiles.save(p));}catch(DataIntegrityViolationException e){return ResponseEntity.status(409).body(Map.of("error","That pet username is already taken."));}}).orElseGet(()->ResponseEntity.notFound().build());}
 @PostMapping("/select-pet/{petId}") public ResponseEntity<?> selectPet(@PathVariable Long petId,HttpSession session){Long ownerId=ownerId(session);if(ownerId==null)return unauthorized();if(!links.existsByOwnerIdAndPetProfileId(ownerId,petId))return ResponseEntity.status(403).body(Map.of("error","This pet does not belong to your account."));if(!profiles.existsById(petId))return ResponseEntity.notFound().build();session.setAttribute("activePetId",petId);return ResponseEntity.ok(profiles.findById(petId).orElseThrow());}
 private void secureAuthenticatedSession(HttpServletRequest request,HttpSession session){try{request.changeSessionId();}catch(IllegalStateException ignored){}session.setMaxInactiveInterval(SESSION_IDLE_SECONDS);session.setAttribute("authenticatedAt",Instant.now().toString());}
 private String passwordError(String p){if(p==null||p.length()<10)return "Password must be at least 10 characters.";if(p.length()>128)return "Password is too long.";if(!p.matches(".*[A-Za-z].*"))return "Password must include a letter.";if(!p.matches(".*\\d.*"))return "Password must include a number.";return null;}
 private ResponseEntity<?> validateProfile(PetProfile p,boolean create){if(create&&(p.getName()==null||p.getName().isBlank()||p.getHandle()==null||p.getHandle().isBlank()))return bad("Pet name and username are required.");if(p.getName()!=null&&p.getName().trim().length()>80)return bad("Pet name can be up to 80 characters.");if(p.getHandle()!=null&&!p.getHandle().isBlank()){String h=normalizeHandle(p.getHandle());if(!h.matches("@[a-z0-9._]{3,30}"))return bad("Username must be 3–30 characters using letters, numbers, dots or underscores.");}if(p.getBirthday()!=null&&p.getBirthday().isAfter(LocalDate.now()))return bad("Birthday cannot be in the future.");if(p.getAdoptionDate()!=null&&p.getAdoptionDate().isAfter(LocalDate.now()))return bad("Adoption date cannot be in the future.");if(p.getBirthday()!=null&&p.getAdoptionDate()!=null&&p.getAdoptionDate().isBefore(p.getBirthday()))return bad("Adoption date cannot be before the pet's birthday.");if(p.getBio()!=null&&p.getBio().length()>1000)return bad("Bio can be up to 1,000 characters.");return null;}
 private void normalizeProfile(PetProfile p){p.setHandle(normalizeHandle(p.getHandle()));p.setAge(calculateAge(p.getBirthday(),p.getAge()));p.setName(clean(p.getName()));p.setSpecies(clean(p.getSpecies()));p.setBreed(clean(p.getBreed()));p.setBio(clean(p.getBio()));p.setLocation(clean(p.getLocation()));p.setGender(clean(p.getGender()));p.setPersonality(clean(p.getPersonality()));p.setFavoriteActivities(clean(p.getFavoriteActivities()));p.setPetPreferences(clean(p.getPetPreferences()));p.setMessagePermission(permission(p.getMessagePermission()));p.setPlayDatePermission(permission(p.getPlayDatePermission()));}
 private String permission(String s){String v=s==null?"EVERYONE":s.trim().toUpperCase();return Set.of("EVERYONE","FOLLOWING","NOBODY").contains(v)?v:"EVERYONE";}private String normalizeHandle(String h){h=h.trim();if(!h.startsWith("@"))h="@"+h;return h.toLowerCase();}private Integer calculateAge(LocalDate b,Integer fallback){if(b==null)return fallback==null?null:Math.max(0,fallback);return Math.max(0,Period.between(b,LocalDate.now()).getYears());}private String clean(String s){if(s==null)return null;String x=s.trim();return x.isEmpty()?null:x;}
 private Map<String,Object> sessionPayload(OwnerAccount o,HttpSession session){List<PetProfile> pets=petsFor(o.getId());Long active=activePet(session);if(active!=null&&!links.existsByOwnerIdAndPetProfileId(o.getId(),active)){active=null;session.removeAttribute("activePetId");}if(active==null&&!pets.isEmpty()){active=pets.get(0).getId();session.setAttribute("activePetId",active);}Map<String,Object>m=new LinkedHashMap<>();m.put("loggedIn",true);m.put("displayName",o.getDisplayName());m.put("email",o.getEmail());m.put("pets",pets);m.put("activePetId",active);return m;}
 private List<PetProfile> petsFor(Long ownerId){List<Long> ids=links.findByOwnerId(ownerId).stream().map(OwnerPetLink::getPetProfileId).toList();return ids.isEmpty()?List.of():profiles.findAllById(ids);}private Long ownerId(HttpSession s){if(s==null)return null;Object x=s.getAttribute("ownerId");return x instanceof Long?(Long)x:null;}private Long activePet(HttpSession s){if(s==null)return null;Object x=s.getAttribute("activePetId");return x instanceof Long?(Long)x:null;}private String norm(String s){return s==null?"":s.trim().toLowerCase();}private ResponseEntity<Map<String,String>> bad(String s){return ResponseEntity.badRequest().body(Map.of("error",s));}private ResponseEntity<Map<String,String>> unauthorized(){return ResponseEntity.status(401).body(Map.of("error","Please log in first."));}
}
