package com.happytails.social;

import jakarta.persistence.*;
import jakarta.servlet.http.HttpSession;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.http.*;
import org.springframework.web.bind.annotation.*;
import java.time.*;
import java.util.*;

@Entity @Table(name="pet_health_profiles",uniqueConstraints=@UniqueConstraint(columnNames="petProfileId"))
class PetHealthProfile extends BaseEntity{Long petProfileId;@Column(length=1500)String allergies;@Column(length=1500)String conditions;String primaryVet;String vetPhone;String emergencyContact;String emergencyPhone;public Long getPetProfileId(){return petProfileId;}public void setPetProfileId(Long v){petProfileId=v;}public String getAllergies(){return allergies;}public void setAllergies(String v){allergies=v;}public String getConditions(){return conditions;}public void setConditions(String v){conditions=v;}public String getPrimaryVet(){return primaryVet;}public void setPrimaryVet(String v){primaryVet=v;}public String getVetPhone(){return vetPhone;}public void setVetPhone(String v){vetPhone=v;}public String getEmergencyContact(){return emergencyContact;}public void setEmergencyContact(String v){emergencyContact=v;}public String getEmergencyPhone(){return emergencyPhone;}public void setEmergencyPhone(String v){emergencyPhone=v;}}
@Entity @Table(name="pet_health_records")
class PetHealthRecord extends BaseEntity{Long petProfileId;String category;String title;String provider;@Column(length=2500)String notes;LocalDate eventDate;LocalDate nextDueDate;String status="COMPLETED";LocalDateTime createdAt=LocalDateTime.now();public Long getPetProfileId(){return petProfileId;}public void setPetProfileId(Long v){petProfileId=v;}public String getCategory(){return category;}public void setCategory(String v){category=v;}public String getTitle(){return title;}public void setTitle(String v){title=v;}public String getProvider(){return provider;}public void setProvider(String v){provider=v;}public String getNotes(){return notes;}public void setNotes(String v){notes=v;}public LocalDate getEventDate(){return eventDate;}public void setEventDate(LocalDate v){eventDate=v;}public LocalDate getNextDueDate(){return nextDueDate;}public void setNextDueDate(LocalDate v){nextDueDate=v;}public String getStatus(){return status;}public void setStatus(String v){status=v;}public LocalDateTime getCreatedAt(){return createdAt;}}
@Entity @Table(name="pet_medications")
class PetMedication extends BaseEntity{Long petProfileId;String name;String dose;String frequency;LocalDate startDate;LocalDate endDate;@Column(length=1500)String notes;boolean active=true;public Long getPetProfileId(){return petProfileId;}public void setPetProfileId(Long v){petProfileId=v;}public String getName(){return name;}public void setName(String v){name=v;}public String getDose(){return dose;}public void setDose(String v){dose=v;}public String getFrequency(){return frequency;}public void setFrequency(String v){frequency=v;}public LocalDate getStartDate(){return startDate;}public void setStartDate(LocalDate v){startDate=v;}public LocalDate getEndDate(){return endDate;}public void setEndDate(LocalDate v){endDate=v;}public String getNotes(){return notes;}public void setNotes(String v){notes=v;}public boolean isActive(){return active;}public void setActive(boolean v){active=v;}}
interface PetHealthProfileRepository extends JpaRepository<PetHealthProfile,Long>{Optional<PetHealthProfile> findByPetProfileId(Long id);}
interface PetHealthRecordRepository extends JpaRepository<PetHealthRecord,Long>{List<PetHealthRecord> findByPetProfileIdOrderByEventDateDesc(Long id);}
interface PetMedicationRepository extends JpaRepository<PetMedication,Long>{List<PetMedication> findByPetProfileIdOrderByActiveDescStartDateDesc(Long id);}
@RestController @RequestMapping("/api/health-passport")
class PetHealthPassportController{
 private final PetHealthProfileRepository profiles;private final PetHealthRecordRepository records;private final PetMedicationRepository medications;private final PetReminderRepository reminders;
 PetHealthPassportController(PetHealthProfileRepository p,PetHealthRecordRepository r,PetMedicationRepository m,PetReminderRepository rem){profiles=p;records=r;medications=m;reminders=rem;}
 private Long active(HttpSession s){Object x=s.getAttribute("activePetId");return x instanceof Long?(Long)x:null;}private ResponseEntity<Map<String,String>> login(){return ResponseEntity.status(401).body(Map.of("error","Please log in and select a pet."));}private String clean(String v){if(v==null)return null;String x=v.trim();return x.isEmpty()?null:x;}
 @GetMapping ResponseEntity<?> passport(HttpSession s){Long pet=active(s);if(pet==null)return login();Map<String,Object> out=new LinkedHashMap<>();out.put("profile",profiles.findByPetProfileId(pet).orElse(null));out.put("records",records.findByPetProfileIdOrderByEventDateDesc(pet));out.put("medications",medications.findByPetProfileIdOrderByActiveDescStartDateDesc(pet));out.put("reminders",reminders.findByPetProfileIdOrderByDueDateAsc(pet));return ResponseEntity.ok(out);}
 @PutMapping("/profile") ResponseEntity<?> saveProfile(@RequestBody PetHealthProfile in,HttpSession s){Long pet=active(s);if(pet==null)return login();PetHealthProfile p=profiles.findByPetProfileId(pet).orElseGet(PetHealthProfile::new);p.setPetProfileId(pet);p.setAllergies(clean(in.getAllergies()));p.setConditions(clean(in.getConditions()));p.setPrimaryVet(clean(in.getPrimaryVet()));p.setVetPhone(clean(in.getVetPhone()));p.setEmergencyContact(clean(in.getEmergencyContact()));p.setEmergencyPhone(clean(in.getEmergencyPhone()));return ResponseEntity.ok(profiles.save(p));}
 @PostMapping("/records") ResponseEntity<?> addRecord(@RequestBody PetHealthRecord r,HttpSession s){Long pet=active(s);if(pet==null)return login();String title=clean(r.getTitle()),cat=clean(r.getCategory());if(title==null||cat==null)return ResponseEntity.badRequest().body(Map.of("error","Category and title are required."));LocalDate event=r.getEventDate()==null?LocalDate.now():r.getEventDate();if(event.isAfter(LocalDate.now()))return ResponseEntity.badRequest().body(Map.of("error","A completed health event cannot be dated in the future."));if(r.getNextDueDate()!=null&&!r.getNextDueDate().isAfter(event))return ResponseEntity.badRequest().body(Map.of("error","Next due date must be after the health event."));r.setPetProfileId(pet);r.setTitle(title);r.setCategory(cat.toUpperCase());r.setProvider(clean(r.getProvider()));r.setNotes(clean(r.getNotes()));r.setEventDate(event);r.setStatus("COMPLETED");PetHealthRecord saved=records.save(r);if(r.getNextDueDate()!=null){String reminderTitle="Next: "+title;boolean exists=reminders.findByPetProfileIdOrderByDueDateAsc(pet).stream().anyMatch(x->!x.isCompleted()&&Objects.equals(x.getDueDate(),r.getNextDueDate())&&reminderTitle.equalsIgnoreCase(x.getTitle()));if(!exists){PetReminder rem=new PetReminder();rem.setPetProfileId(pet);rem.setType(cat.toUpperCase());rem.setTitle(reminderTitle);rem.setDueDate(r.getNextDueDate());reminders.save(rem);}}return ResponseEntity.status(201).body(saved);}
 @DeleteMapping("/records/{id}") ResponseEntity<?> deleteRecord(@PathVariable Long id,HttpSession s){Long pet=active(s);if(pet==null)return login();return records.findById(id).<ResponseEntity<?>>map(r->{if(!Objects.equals(r.getPetProfileId(),pet))return ResponseEntity.status(403).body(Map.of("error","This health record does not belong to your pet."));records.delete(r);return ResponseEntity.ok(Map.of("deleted",true));}).orElseGet(()->ResponseEntity.notFound().build());}
 @PostMapping("/medications") ResponseEntity<?> addMedication(@RequestBody PetMedication m,HttpSession s){Long pet=active(s);if(pet==null)return login();String name=clean(m.getName());if(name==null)return ResponseEntity.badRequest().body(Map.of("error","Medication name is required."));LocalDate start=m.getStartDate()==null?LocalDate.now():m.getStartDate();if(m.getEndDate()!=null&&m.getEndDate().isBefore(start))return ResponseEntity.badRequest().body(Map.of("error","Medication end date cannot be before its start date."));m.setPetProfileId(pet);m.setName(name);m.setDose(clean(m.getDose()));m.setFrequency(clean(m.getFrequency()));m.setNotes(clean(m.getNotes()));m.setStartDate(start);m.setActive(m.getEndDate()==null||!m.getEndDate().isBefore(LocalDate.now()));return ResponseEntity.status(201).body(medications.save(m));}
 @PatchMapping("/medications/{id}/stop") ResponseEntity<?> stopMedication(@PathVariable Long id,HttpSession s){Long pet=active(s);if(pet==null)return login();return medications.findById(id).<ResponseEntity<?>>map(m->{if(!Objects.equals(m.getPetProfileId(),pet))return ResponseEntity.status(403).body(Map.of("error","This medication does not belong to your pet."));if(!m.isActive())return ResponseEntity.ok(m);m.setActive(false);if(m.getEndDate()==null)m.setEndDate(LocalDate.now());return ResponseEntity.ok(medications.save(m));}).orElseGet(()->ResponseEntity.notFound().build());}
}
