package com.happytails.social;

import jakarta.servlet.http.HttpSession;
import org.springframework.http.*;
import org.springframework.web.bind.annotation.*;
import java.util.*;

@RestController
@RequestMapping("/api/social")
@CrossOrigin
public class SocialController {
  private final PetProfileRepository profiles; private final SocialPostRepository posts; private final PetFollowRepository follows;
  private final FriendRequestRepository requests; private final PetReminderRepository reminders; private final PlayDateRepository playDates;
  private final MeetupRepository meetups; private final PetSitterRepository sitters; private final PetOrderRepository orders; private final PetMemoryRepository memories;

  public SocialController(PetProfileRepository profiles, SocialPostRepository posts, PetFollowRepository follows, FriendRequestRepository requests,
      PetReminderRepository reminders, PlayDateRepository playDates, MeetupRepository meetups, PetSitterRepository sitters,
      PetOrderRepository orders, PetMemoryRepository memories){this.profiles=profiles;this.posts=posts;this.follows=follows;this.requests=requests;this.reminders=reminders;this.playDates=playDates;this.meetups=meetups;this.sitters=sitters;this.orders=orders;this.memories=memories;}

  @GetMapping("/profiles") public List<Map<String,Object>> profiles(HttpSession session){Long viewer=activePet(session);return profiles.findAll().stream().map(p->publicProfile(p,viewer)).toList();}
  @PostMapping("/profiles") public ResponseEntity<?> createProfile(){return ResponseEntity.status(403).body(Map.of("error","Create pets through your account onboarding."));}
  @GetMapping("/profiles/{id}") public ResponseEntity<?> profile(@PathVariable Long id,HttpSession session){Long viewer=activePet(session);return profiles.findById(id).<ResponseEntity<?>>map(p->ResponseEntity.ok(publicProfile(p,viewer))).orElseGet(()->ResponseEntity.notFound().build());}

  @GetMapping("/posts") public List<SocialPost> posts(HttpSession session){Long viewer=activePet(session);return posts.findAll().stream().filter(p->canViewPosts(viewer,p.getPetProfileId())).toList();}
  @GetMapping("/profiles/{id}/posts") public List<SocialPost> postsByPet(@PathVariable Long id,HttpSession session){Long viewer=activePet(session);return canViewPosts(viewer,id)?posts.findByPetProfileIdOrderByCreatedAtDesc(id):List.of();}
  @PostMapping("/posts") public ResponseEntity<?> createPost(@RequestBody SocialPost p,HttpSession session){Long me=activePet(session);if(me==null)return unauthorized();p.setPetProfileId(me);if(p.getCaption()==null||p.getCaption().trim().isEmpty())return ResponseEntity.badRequest().body(Map.of("error","Write something about your pet first."));return ResponseEntity.status(201).body(posts.save(p));}
  @PostMapping("/posts/{id}/paw") public ResponseEntity<?> paw(@PathVariable Long id,HttpSession session){Long me=activePet(session);if(me==null)return unauthorized();return posts.findById(id).<ResponseEntity<?>>map(p->{if(!canViewPosts(me,p.getPetProfileId()))return ResponseEntity.status(403).body(Map.of("error","This post is private."));p.setPawCount(p.getPawCount()+1);return ResponseEntity.ok(posts.save(p));}).orElseGet(()->ResponseEntity.notFound().build());}

  @PostMapping("/follows") public ResponseEntity<?> follow(@RequestBody PetFollow f,HttpSession session){Long me=activePet(session);if(me==null)return unauthorized();Long target=f.getFollowingPetId();if(target==null||!profiles.existsById(target))return ResponseEntity.badRequest().body(Map.of("error","Pet profile not found."));if(Objects.equals(me,target))return ResponseEntity.badRequest().body(Map.of("error","You cannot follow your own pet profile."));if(follows.existsByFollowerPetIdAndFollowingPetId(me,target))return ResponseEntity.status(409).body(Map.of("error","Already following."));f.setFollowerPetId(me);PetFollow saved=follows.save(f);profiles.findById(me).ifPresent(p->{p.setFollowing(p.getFollowing()+1);profiles.save(p);});profiles.findById(target).ifPresent(p->{p.setFollowers(p.getFollowers()+1);profiles.save(p);});return ResponseEntity.status(201).body(saved);}
  @GetMapping("/profiles/{id}/followers") public List<PetFollow> followers(@PathVariable Long id){return follows.findByFollowingPetId(id);}
  @GetMapping("/profiles/{id}/following") public List<PetFollow> following(@PathVariable Long id){return follows.findByFollowerPetId(id);}

  @PostMapping("/friend-requests") public ResponseEntity<?> request(@RequestBody FriendRequest r,HttpSession session){Long me=activePet(session);if(me==null)return unauthorized();Long target=r.getToPetId();if(target==null||!profiles.existsById(target))return ResponseEntity.badRequest().body(Map.of("error","Pet profile not found."));if(Objects.equals(me,target))return ResponseEntity.badRequest().body(Map.of("error","You cannot send a friend request to your own pet profile."));if(requests.existsByFromPetIdAndToPetIdAndStatus(me,target,"PENDING")||requests.existsByFromPetIdAndToPetIdAndStatus(target,me,"PENDING"))return ResponseEntity.status(409).body(Map.of("error","A friend request is already pending."));if(areFriends(me,target))return ResponseEntity.status(409).body(Map.of("error","These pets are already friends."));r.setFromPetId(me);r.setStatus("PENDING");return ResponseEntity.status(201).body(requests.save(r));}
  @GetMapping("/profiles/{id}/friend-requests") public ResponseEntity<?> pending(@PathVariable Long id,HttpSession session){Long me=activePet(session);if(me==null)return unauthorized();if(!Objects.equals(me,id))return ResponseEntity.status(403).body(Map.of("error","Friend requests are private."));return ResponseEntity.ok(requests.findByToPetIdAndStatus(id,"PENDING"));}
  @PatchMapping("/friend-requests/{id}/{status}") public ResponseEntity<?> updateRequest(@PathVariable Long id,@PathVariable String status,HttpSession session){Long me=activePet(session);if(me==null)return unauthorized();String next=status.toUpperCase();if(!Set.of("ACCEPTED","DECLINED").contains(next))return ResponseEntity.badRequest().body(Map.of("error","Invalid friend request status."));return requests.findById(id).<ResponseEntity<?>>map(r->{if(!Objects.equals(me,r.getToPetId()))return ResponseEntity.status(403).body(Map.of("error","Only the invited pet can respond."));if(!"PENDING".equalsIgnoreCase(r.getStatus()))return ResponseEntity.status(409).body(Map.of("error","This request has already been handled."));r.setStatus(next);return ResponseEntity.ok(requests.save(r));}).orElseGet(()->ResponseEntity.notFound().build());}

  @GetMapping("/profiles/{id}/reminders") public ResponseEntity<?> reminders(@PathVariable Long id,HttpSession session){Long me=activePet(session);if(me==null)return unauthorized();if(!Objects.equals(me,id))return ResponseEntity.status(403).body(Map.of("error","Care reminders are private."));return ResponseEntity.ok(reminders.findByPetProfileIdOrderByDueDateAsc(id));}
  @PostMapping("/reminders") public ResponseEntity<?> reminder(@RequestBody PetReminder r,HttpSession session){Long me=activePet(session);if(me==null)return unauthorized();r.setPetProfileId(me);return ResponseEntity.status(201).body(reminders.save(r));}
  @PatchMapping("/reminders/{id}/complete") public ResponseEntity<?> complete(@PathVariable Long id,HttpSession session){Long me=activePet(session);if(me==null)return unauthorized();return reminders.findById(id).<ResponseEntity<?>>map(r->{if(!Objects.equals(me,r.getPetProfileId()))return ResponseEntity.status(403).body(Map.of("error","This reminder does not belong to your pet."));r.setCompleted(true);return ResponseEntity.ok(reminders.save(r));}).orElseGet(()->ResponseEntity.notFound().build());}

  @PostMapping("/play-dates") public ResponseEntity<?> playDate(@RequestBody PlayDate p,HttpSession session){Long active=activePet(session);if(active==null)return unauthorized();if(p.getGuestPetId()==null)return ResponseEntity.badRequest().body(Map.of("error","Choose a valid pet."));Optional<PetProfile> guest=profiles.findById(p.getGuestPetId());if(guest.isEmpty())return ResponseEntity.badRequest().body(Map.of("error","Choose a valid pet."));if(Objects.equals(active,p.getGuestPetId()))return ResponseEntity.badRequest().body(Map.of("error","Choose another pet for the play date."));String permission=guest.get().getPlayDatePermission()==null?"EVERYONE":guest.get().getPlayDatePermission();if("NOBODY".equalsIgnoreCase(permission))return ResponseEntity.status(403).body(Map.of("error",guest.get().getName()+" is not accepting play-date requests."));if("FOLLOWING".equalsIgnoreCase(permission)&&!follows.existsByFollowerPetIdAndFollowingPetId(guest.get().getId(),active))return ResponseEntity.status(403).body(Map.of("error","Only pets this account follows can send play-date requests."));p.setHostPetId(active);p.setStatus("PENDING");return ResponseEntity.status(201).body(playDates.save(p));}
  @GetMapping("/profiles/{id}/play-dates") public ResponseEntity<?> playDates(@PathVariable Long id,HttpSession session){Long me=activePet(session);if(me==null)return unauthorized();if(!Objects.equals(me,id))return ResponseEntity.status(403).body(Map.of("error","Play dates are private."));return ResponseEntity.ok(playDates.findByHostPetIdOrGuestPetIdOrderByScheduledAtAsc(id,id));}
  @PatchMapping("/play-dates/{id}/{status}") public ResponseEntity<?> updatePlayDate(@PathVariable Long id,@PathVariable String status,HttpSession session){Long active=activePet(session);if(active==null)return unauthorized();String next=status.toUpperCase();if(!Set.of("ACCEPTED","DECLINED","CANCELLED").contains(next))return ResponseEntity.badRequest().body(Map.of("error","Invalid play date status."));return playDates.findById(id).<ResponseEntity<?>>map(p->{boolean guest=Objects.equals(active,p.getGuestPetId()),host=Objects.equals(active,p.getHostPetId());if(next.equals("CANCELLED")&&!host)return ResponseEntity.status(403).body(Map.of("error","Only the pet who created this play date can cancel it."));if((next.equals("ACCEPTED")||next.equals("DECLINED"))&&!guest)return ResponseEntity.status(403).body(Map.of("error","Only the invited pet can respond."));p.setStatus(next);return ResponseEntity.ok(playDates.save(p));}).orElseGet(()->ResponseEntity.notFound().build());}

  @GetMapping("/meetups") public List<Meetup> meetups(){return meetups.findAllByOrderByScheduledAtAsc();}
  @PostMapping("/meetups/{id}/join") public ResponseEntity<?> join(@PathVariable Long id,HttpSession session){if(activePet(session)==null)return unauthorized();return meetups.findById(id).<ResponseEntity<?>>map(m->{m.setAttendeeCount(m.getAttendeeCount()+1);return ResponseEntity.ok(meetups.save(m));}).orElseGet(()->ResponseEntity.notFound().build());}

  @GetMapping("/sitters") public List<PetSitter> sitters(){return sitters.findByAvailableTrue();}

  @GetMapping("/profiles/{id}/orders") public ResponseEntity<?> orders(@PathVariable Long id,HttpSession session){Long me=activePet(session);if(me==null)return unauthorized();if(!Objects.equals(me,id))return ResponseEntity.status(403).body(Map.of("error","Orders are private."));return ResponseEntity.ok(orders.findByPetProfileIdOrderByCreatedAtDesc(id));}
  @PostMapping("/orders") public ResponseEntity<?> order(@RequestBody PetOrder o,HttpSession session){Long me=activePet(session);if(me==null)return unauthorized();o.setPetProfileId(me);return ResponseEntity.status(201).body(orders.save(o));}

  @GetMapping("/profiles/{id}/memories") public ResponseEntity<?> memories(@PathVariable Long id,HttpSession session){Long me=activePet(session);if(me==null)return unauthorized();if(!Objects.equals(me,id))return ResponseEntity.status(403).body(Map.of("error","Memories are private."));return ResponseEntity.ok(memories.findByPetProfileIdOrderByMemoryDateDesc(id));}
  @PostMapping("/memories") public ResponseEntity<?> memory(@RequestBody PetMemory m,HttpSession session){Long me=activePet(session);if(me==null)return unauthorized();m.setPetProfileId(me);return ResponseEntity.status(201).body(memories.save(m));}

  @GetMapping("/health") public Map<String,Object> health(){return Map.of("status","UP","modules",List.of("profiles","posts","follows","friends","reminders","playDates","meetups","sitters","orders","memories"));}
  private Long activePet(HttpSession session){Object x=session.getAttribute("activePetId");return x instanceof Long?(Long)x:null;}
  private ResponseEntity<Map<String,String>> unauthorized(){return ResponseEntity.status(401).body(Map.of("error","Please log in first."));}
  private boolean areFriends(Long a,Long b){if(a==null||b==null)return false;return requests.existsByFromPetIdAndToPetIdAndStatus(a,b,"ACCEPTED")||requests.existsByFromPetIdAndToPetIdAndStatus(b,a,"ACCEPTED");}
  private boolean canViewPosts(Long viewer,Long owner){if(Objects.equals(viewer,owner))return true;Optional<PetProfile> p=profiles.findById(owner);return p.isPresent()&&(!p.get().isPrivateAccount()||areFriends(viewer,owner));}
  private Map<String,Object> publicProfile(PetProfile p,Long viewer){boolean self=Objects.equals(viewer,p.getId()),friend=areFriends(viewer,p.getId());Map<String,Object> m=new LinkedHashMap<>();m.put("id",p.getId());m.put("handle",p.getHandle());m.put("name",p.getName());m.put("species",p.getSpecies());m.put("breed",p.getBreed());m.put("bio",p.getBio());m.put("avatarUrl",p.getAvatarUrl());m.put("location",self||p.isShowLocation()?p.getLocation():"Location private");m.put("birthday",p.getBirthday());m.put("adoptionDate",self?p.getAdoptionDate():null);m.put("age",p.getAge());m.put("gender",p.getGender());m.put("personality",p.getPersonality());m.put("favoriteActivities",p.getFavoriteActivities());m.put("petPreferences",self?p.getPetPreferences():null);m.put("privateAccount",p.isPrivateAccount());m.put("showLocation",self?p.isShowLocation():false);m.put("messagePermission",self?p.getMessagePermission():null);m.put("playDatePermission",self?p.getPlayDatePermission():null);m.put("followers",p.getFollowers());m.put("following",p.getFollowing());m.put("contentVisible",!p.isPrivateAccount()||self||friend);return m;}
}
