package com.happytails.social;

import jakarta.servlet.http.HttpSession;
import org.springframework.http.*;
import org.springframework.web.bind.annotation.*;
import java.time.*;
import java.util.*;

@RestController @RequestMapping("/api/social") @CrossOrigin
public class SocialController {
 private final PetProfileRepository profiles;private final SocialPostRepository posts;private final PetFollowRepository follows;private final FriendRequestRepository requests;private final PetReminderRepository reminders;private final PlayDateRepository playDates;private final MeetupRepository meetups;private final MeetupAttendeeRepository meetupAttendees;private final PetSitterRepository sitters;private final PetOrderRepository orders;private final PetMemoryRepository memories;private final PetBlockRepository blocks;
 public SocialController(PetProfileRepository profiles,SocialPostRepository posts,PetFollowRepository follows,FriendRequestRepository requests,PetReminderRepository reminders,PlayDateRepository playDates,MeetupRepository meetups,MeetupAttendeeRepository meetupAttendees,PetSitterRepository sitters,PetOrderRepository orders,PetMemoryRepository memories,PetBlockRepository blocks){this.profiles=profiles;this.posts=posts;this.follows=follows;this.requests=requests;this.reminders=reminders;this.playDates=playDates;this.meetups=meetups;this.meetupAttendees=meetupAttendees;this.sitters=sitters;this.orders=orders;this.memories=memories;this.blocks=blocks;}
 @GetMapping("/profiles") public List<Map<String,Object>> profiles(HttpSession s){Long v=activePet(s);return profiles.findAll().stream().filter(p->v==null||Objects.equals(v,p.getId())||!blockedEitherWay(v,p.getId())).map(p->publicProfile(p,v)).toList();}
 @PostMapping("/profiles") public ResponseEntity<?> createProfile(){return ResponseEntity.status(403).body(Map.of("error","Create pets through your account onboarding."));}
 @GetMapping("/profiles/{id}") public ResponseEntity<?> profile(@PathVariable Long id,HttpSession s){Long v=activePet(s);if(v!=null&&!Objects.equals(v,id)&&blockedEitherWay(v,id))return ResponseEntity.status(403).body(Map.of("error","This pet profile is unavailable."));return profiles.findById(id).<ResponseEntity<?>>map(p->ResponseEntity.ok(publicProfile(p,v))).orElseGet(()->ResponseEntity.notFound().build());}
 @GetMapping("/posts") public List<SocialPost> posts(HttpSession s){Long v=activePet(s);return posts.findAll().stream().filter(p->canViewPosts(v,p.getPetProfileId())).toList();}
 @GetMapping("/profiles/{id}/posts") public List<SocialPost> postsByPet(@PathVariable Long id,HttpSession s){Long v=activePet(s);return canViewPosts(v,id)?posts.findByPetProfileIdOrderByCreatedAtDesc(id):List.of();}
 @PostMapping("/posts") public ResponseEntity<?> createPost(@RequestBody SocialPost p,HttpSession s){Long me=activePet(s);if(me==null)return unauthorized();String c=p.getCaption()==null?"":p.getCaption().trim();if(c.isEmpty())return ResponseEntity.badRequest().body(Map.of("error","Write something about your pet first."));if(c.length()>2000)return ResponseEntity.badRequest().body(Map.of("error","Posts can be up to 2,000 characters."));p.setPetProfileId(me);p.setCaption(c);return ResponseEntity.status(201).body(posts.save(p));}
 @PostMapping("/posts/{id}/paw") public ResponseEntity<?> paw(@PathVariable Long id,HttpSession s){Long me=activePet(s);if(me==null)return unauthorized();return posts.findById(id).<ResponseEntity<?>>map(p->{if(!canViewPosts(me,p.getPetProfileId()))return ResponseEntity.status(403).body(Map.of("error","This post is unavailable."));p.setPawCount(p.getPawCount()+1);return ResponseEntity.ok(posts.save(p));}).orElseGet(()->ResponseEntity.notFound().build());}
 @PostMapping("/follows") public ResponseEntity<?> follow(@RequestBody PetFollow f,HttpSession s){Long me=activePet(s),target=f.getFollowingPetId();if(me==null)return unauthorized();if(target==null||!profiles.existsById(target))return ResponseEntity.badRequest().body(Map.of("error","Pet profile not found."));if(Objects.equals(me,target))return ResponseEntity.badRequest().body(Map.of("error","You cannot follow your own pet profile."));if(blockedEitherWay(me,target))return ResponseEntity.status(403).body(Map.of("error","You cannot follow this pet account."));if(follows.existsByFollowerPetIdAndFollowingPetId(me,target))return ResponseEntity.status(409).body(Map.of("error","Already following."));f.setFollowerPetId(me);PetFollow saved=follows.save(f);profiles.findById(me).ifPresent(p->{p.setFollowing(p.getFollowing()+1);profiles.save(p);});profiles.findById(target).ifPresent(p->{p.setFollowers(p.getFollowers()+1);profiles.save(p);});return ResponseEntity.status(201).body(saved);}
 @GetMapping("/profiles/{id}/followers") public ResponseEntity<?> followers(@PathVariable Long id,HttpSession s){Long me=activePet(s);if(me!=null&&!Objects.equals(me,id)&&blockedEitherWay(me,id))return ResponseEntity.status(403).body(Map.of("error","This pet profile is unavailable."));return ResponseEntity.ok(follows.findByFollowingPetId(id));}
 @GetMapping("/profiles/{id}/following") public ResponseEntity<?> following(@PathVariable Long id,HttpSession s){Long me=activePet(s);if(me!=null&&!Objects.equals(me,id)&&blockedEitherWay(me,id))return ResponseEntity.status(403).body(Map.of("error","This pet profile is unavailable."));return ResponseEntity.ok(follows.findByFollowerPetId(id));}
 @PostMapping("/friend-requests") public ResponseEntity<?> request(@RequestBody FriendRequest r,HttpSession s){Long me=activePet(s),target=r.getToPetId();if(me==null)return unauthorized();if(target==null||!profiles.existsById(target))return ResponseEntity.badRequest().body(Map.of("error","Pet profile not found."));if(Objects.equals(me,target))return ResponseEntity.badRequest().body(Map.of("error","You cannot send a friend request to your own pet profile."));if(blockedEitherWay(me,target))return ResponseEntity.status(403).body(Map.of("error","You cannot connect with this pet account."));if(requests.existsByFromPetIdAndToPetIdAndStatus(me,target,"PENDING")||requests.existsByFromPetIdAndToPetIdAndStatus(target,me,"PENDING"))return ResponseEntity.status(409).body(Map.of("error","A friend request is already pending."));if(areFriends(me,target))return ResponseEntity.status(409).body(Map.of("error","These pets are already friends."));r.setFromPetId(me);r.setStatus("PENDING");return ResponseEntity.status(201).body(requests.save(r));}
 @GetMapping("/profiles/{id}/friend-requests") public ResponseEntity<?> pending(@PathVariable Long id,HttpSession s){Long me=activePet(s);if(me==null)return unauthorized();if(!Objects.equals(me,id))return ResponseEntity.status(403).body(Map.of("error","Friend requests are private."));return ResponseEntity.ok(requests.findByToPetIdAndStatus(id,"PENDING").stream().filter(r->!blockedEitherWay(me,r.getFromPetId())).toList());}
 @PatchMapping("/friend-requests/{id}/{status}") public ResponseEntity<?> updateRequest(@PathVariable Long id,@PathVariable String status,HttpSession s){Long me=activePet(s);if(me==null)return unauthorized();String next=status.toUpperCase();if(!Set.of("ACCEPTED","DECLINED").contains(next))return ResponseEntity.badRequest().body(Map.of("error","Invalid friend request status."));return requests.findById(id).<ResponseEntity<?>>map(r->{if(!Objects.equals(me,r.getToPetId()))return ResponseEntity.status(403).body(Map.of("error","Only the invited pet can respond."));if(blockedEitherWay(r.getFromPetId(),r.getToPetId()))return ResponseEntity.status(403).body(Map.of("error","This pet connection is unavailable."));if(!"PENDING".equalsIgnoreCase(r.getStatus()))return ResponseEntity.status(409).body(Map.of("error","This request has already been handled."));r.setStatus(next);return ResponseEntity.ok(requests.save(r));}).orElseGet(()->ResponseEntity.notFound().build());}
 @GetMapping("/profiles/{id}/reminders") public ResponseEntity<?> reminders(@PathVariable Long id,HttpSession s){Long me=activePet(s);if(me==null)return unauthorized();if(!Objects.equals(me,id))return ResponseEntity.status(403).body(Map.of("error","Care reminders are private."));return ResponseEntity.ok(reminders.findByPetProfileIdOrderByDueDateAsc(id));}
 @PostMapping("/reminders") public ResponseEntity<?> reminder(@RequestBody PetReminder r,HttpSession s){Long me=activePet(s);if(me==null)return unauthorized();String title=r.getTitle()==null?"":r.getTitle().trim();if(title.isEmpty())return ResponseEntity.badRequest().body(Map.of("error","Reminder title is required."));if(r.getDueDate()==null)return ResponseEntity.badRequest().body(Map.of("error","Reminder due date is required."));r.setPetProfileId(me);r.setTitle(title);r.setCompleted(false);return ResponseEntity.status(201).body(reminders.save(r));}
 @PatchMapping("/reminders/{id}/complete") public ResponseEntity<?> complete(@PathVariable Long id,HttpSession s){Long me=activePet(s);if(me==null)return unauthorized();return reminders.findById(id).<ResponseEntity<?>>map(r->{if(!Objects.equals(me,r.getPetProfileId()))return ResponseEntity.status(403).body(Map.of("error","This reminder does not belong to your pet."));r.setCompleted(true);return ResponseEntity.ok(reminders.save(r));}).orElseGet(()->ResponseEntity.notFound().build());}
 @PostMapping("/play-dates") public ResponseEntity<?> playDate(@RequestBody PlayDate p,HttpSession s){Long me=activePet(s);if(me==null)return unauthorized();if(p.getGuestPetId()==null||!profiles.existsById(p.getGuestPetId()))return ResponseEntity.badRequest().body(Map.of("error","Choose a valid pet."));if(Objects.equals(me,p.getGuestPetId()))return ResponseEntity.badRequest().body(Map.of("error","Choose another pet for the play date."));if(p.getScheduledAt()==null||!p.getScheduledAt().isAfter(LocalDateTime.now()))return ResponseEntity.badRequest().body(Map.of("error","Play date must be scheduled in the future."));if(p.getLocation()==null||p.getLocation().trim().isEmpty())return ResponseEntity.badRequest().body(Map.of("error","Choose a play-date location."));if(blockedEitherWay(me,p.getGuestPetId()))return ResponseEntity.status(403).body(Map.of("error","Play dates are unavailable between these pet accounts."));PetProfile guest=profiles.findById(p.getGuestPetId()).orElseThrow();String permission=guest.getPlayDatePermission()==null?"EVERYONE":guest.getPlayDatePermission();if("NOBODY".equalsIgnoreCase(permission))return ResponseEntity.status(403).body(Map.of("error",guest.getName()+" is not accepting play-date requests."));if("FOLLOWING".equalsIgnoreCase(permission)&&!follows.existsByFollowerPetIdAndFollowingPetId(guest.getId(),me))return ResponseEntity.status(403).body(Map.of("error","Only pets this account follows can send play-date requests."));p.setHostPetId(me);p.setLocation(p.getLocation().trim());p.setStatus("PENDING");return ResponseEntity.status(201).body(playDates.save(p));}
 @GetMapping("/profiles/{id}/play-dates") public ResponseEntity<?> playDates(@PathVariable Long id,HttpSession s){Long me=activePet(s);if(me==null)return unauthorized();if(!Objects.equals(me,id))return ResponseEntity.status(403).body(Map.of("error","Play dates are private."));return ResponseEntity.ok(playDates.findByHostPetIdOrGuestPetIdOrderByScheduledAtAsc(id,id).stream().filter(p->{Long o=Objects.equals(id,p.getHostPetId())?p.getGuestPetId():p.getHostPetId();return !blockedEitherWay(id,o);}).toList());}
 @PatchMapping("/play-dates/{id}/{status}") public ResponseEntity<?> updatePlayDate(@PathVariable Long id,@PathVariable String status,HttpSession s){Long me=activePet(s);if(me==null)return unauthorized();String next=status.toUpperCase();if(!Set.of("ACCEPTED","DECLINED","CANCELLED").contains(next))return ResponseEntity.badRequest().body(Map.of("error","Invalid play date status."));return playDates.findById(id).<ResponseEntity<?>>map(p->{if(blockedEitherWay(p.getHostPetId(),p.getGuestPetId()))return ResponseEntity.status(403).body(Map.of("error","This play date is unavailable."));boolean guest=Objects.equals(me,p.getGuestPetId()),host=Objects.equals(me,p.getHostPetId());if(!"PENDING".equalsIgnoreCase(p.getStatus())&& !next.equals("CANCELLED"))return ResponseEntity.status(409).body(Map.of("error","This play date has already been handled."));if(next.equals("CANCELLED")&&!host)return ResponseEntity.status(403).body(Map.of("error","Only the pet who created this play date can cancel it."));if((next.equals("ACCEPTED")||next.equals("DECLINED"))&&!guest)return ResponseEntity.status(403).body(Map.of("error","Only the invited pet can respond."));p.setStatus(next);return ResponseEntity.ok(playDates.save(p));}).orElseGet(()->ResponseEntity.notFound().build());}
 @GetMapping("/meetups") public List<Map<String,Object>> meetups(HttpSession s){Long me=activePet(s);return meetups.findAllByOrderByScheduledAtAsc().stream().map(m->{Map<String,Object>x=new LinkedHashMap<>();x.put("id",m.getId());x.put("title",m.getTitle());x.put("description",m.getDescription());x.put("location",m.getLocation());x.put("scheduledAt",m.getScheduledAt());x.put("attendeeCount",meetupAttendees.countByMeetupId(m.getId()));x.put("joined",me!=null&&meetupAttendees.existsByMeetupIdAndPetProfileId(m.getId(),me));x.put("past",m.getScheduledAt()!=null&&m.getScheduledAt().isBefore(LocalDateTime.now()));return x;}).toList();}
 @PostMapping("/meetups/{id}/join") public ResponseEntity<?> join(@PathVariable Long id,HttpSession s){Long me=activePet(s);if(me==null)return unauthorized();return meetups.findById(id).<ResponseEntity<?>>map(m->{if(m.getScheduledAt()==null||!m.getScheduledAt().isAfter(LocalDateTime.now()))return ResponseEntity.status(409).body(Map.of("error","This meetup has already started or ended."));if(meetupAttendees.existsByMeetupIdAndPetProfileId(id,me))return ResponseEntity.ok(Map.of("joined",true,"attendeeCount",meetupAttendees.countByMeetupId(id)));MeetupAttendee a=new MeetupAttendee();a.setMeetupId(id);a.setPetProfileId(me);meetupAttendees.save(a);m.setAttendeeCount((int)meetupAttendees.countByMeetupId(id));meetups.save(m);return ResponseEntity.ok(Map.of("joined",true,"attendeeCount",m.getAttendeeCount()));}).orElseGet(()->ResponseEntity.notFound().build());}
 @DeleteMapping("/meetups/{id}/join") public ResponseEntity<?> leaveMeetup(@PathVariable Long id,HttpSession s){Long me=activePet(s);if(me==null)return unauthorized();Optional<MeetupAttendee>a=meetupAttendees.findByMeetupIdAndPetProfileId(id,me);if(a.isPresent())meetupAttendees.delete(a.get());return meetups.findById(id).<ResponseEntity<?>>map(m->{m.setAttendeeCount((int)meetupAttendees.countByMeetupId(id));meetups.save(m);return ResponseEntity.ok(Map.of("joined",false,"attendeeCount",m.getAttendeeCount()));}).orElseGet(()->ResponseEntity.notFound().build());}
 @GetMapping("/sitters") public List<PetSitter> sitters(){return sitters.findByAvailableTrue();}
 @GetMapping("/profiles/{id}/orders") public ResponseEntity<?> orders(@PathVariable Long id,HttpSession s){Long me=activePet(s);if(me==null)return unauthorized();if(!Objects.equals(me,id))return ResponseEntity.status(403).body(Map.of("error","Orders are private."));return ResponseEntity.ok(orders.findByPetProfileIdOrderByCreatedAtDesc(id));}
 @PostMapping("/orders") public ResponseEntity<?> order(@RequestBody PetOrder o,HttpSession s){Long me=activePet(s);if(me==null)return unauthorized();String item=o.getItemName()==null?"":o.getItemName().trim();if(item.isEmpty()||o.getQuantity()<=0||o.getTotalAmount()<0)return ResponseEntity.badRequest().body(Map.of("error","Choose a valid item, quantity and total."));o.setPetProfileId(me);o.setItemName(item);o.setStatus("PLACED");return ResponseEntity.status(201).body(orders.save(o));}
 @GetMapping("/profiles/{id}/memories") public ResponseEntity<?> memories(@PathVariable Long id,HttpSession s){Long me=activePet(s);if(me==null)return unauthorized();if(!Objects.equals(me,id))return ResponseEntity.status(403).body(Map.of("error","Memories are private."));return ResponseEntity.ok(memories.findByPetProfileIdOrderByMemoryDateDesc(id));}
 @PostMapping("/memories") public ResponseEntity<?> memory(@RequestBody PetMemory m,HttpSession s){Long me=activePet(s);if(me==null)return unauthorized();String title=m.getTitle()==null?"":m.getTitle().trim();if(title.isEmpty()||m.getMemoryDate()==null)return ResponseEntity.badRequest().body(Map.of("error","Memory title and date are required."));if(m.getMemoryDate().isAfter(LocalDate.now()))return ResponseEntity.badRequest().body(Map.of("error","A memory cannot be dated in the future."));m.setPetProfileId(me);m.setTitle(title);return ResponseEntity.status(201).body(memories.save(m));}
 @GetMapping("/health") public Map<String,Object> health(){return Map.of("status","UP","modules",List.of("profiles","posts","follows","friends","reminders","playDates","meetups","sitters","orders","memories"));}
 private Long activePet(HttpSession s){Object x=s.getAttribute("activePetId");return x instanceof Long?(Long)x:null;}private ResponseEntity<Map<String,String>> unauthorized(){return ResponseEntity.status(401).body(Map.of("error","Please log in first."));}private boolean blockedEitherWay(Long a,Long b){return a!=null&&b!=null&&(blocks.existsByBlockerPetIdAndBlockedPetId(a,b)||blocks.existsByBlockerPetIdAndBlockedPetId(b,a));}private boolean areFriends(Long a,Long b){if(a==null||b==null||blockedEitherWay(a,b))return false;return requests.existsByFromPetIdAndToPetIdAndStatus(a,b,"ACCEPTED")||requests.existsByFromPetIdAndToPetIdAndStatus(b,a,"ACCEPTED");}private boolean canViewPosts(Long v,Long owner){if(Objects.equals(v,owner))return true;if(v!=null&&blockedEitherWay(v,owner))return false;Optional<PetProfile>p=profiles.findById(owner);return p.isPresent()&&(!p.get().isPrivateAccount()||areFriends(v,owner));}
 private Map<String,Object> publicProfile(PetProfile p,Long v){boolean self=Objects.equals(v,p.getId()),friend=areFriends(v,p.getId());Map<String,Object>m=new LinkedHashMap<>();m.put("id",p.getId());m.put("handle",p.getHandle());m.put("name",p.getName());m.put("species",p.getSpecies());m.put("breed",p.getBreed());m.put("bio",p.getBio());m.put("avatarUrl",p.getAvatarUrl());m.put("location",self||p.isShowLocation()?p.getLocation():"Location private");m.put("birthday",p.getBirthday());m.put("adoptionDate",self?p.getAdoptionDate():null);m.put("age",p.getAge());m.put("gender",p.getGender());m.put("personality",p.getPersonality());m.put("favoriteActivities",p.getFavoriteActivities());m.put("petPreferences",self?p.getPetPreferences():null);m.put("privateAccount",p.isPrivateAccount());m.put("showLocation",self?p.isShowLocation():false);m.put("messagePermission",self?p.getMessagePermission():null);m.put("playDatePermission",self?p.getPlayDatePermission():null);m.put("followers",p.getFollowers());m.put("following",p.getFollowing());m.put("contentVisible",!p.isPrivateAccount()||self||friend);return m;}
}
